[package]
name = "lxbench"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "lxbench"
path = "src/lxbench.rs"

[dependencies]
libc = "0.2"
m3impl = { path = "../../../src/libs/rust/m3impl", features = ["linux"] }
