[package]
name = "starter"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "starter"
path = "src/starter.rs"

[dependencies]
libc = "0.2"
base = { path = "../../../libs/rust/base", features = ["linux"] }
