[package]
name = "base"
version = "0.1.0"
edition = "2018"

[lib]
name = "base"
crate-type = ["rlib"]

[dependencies]
bitflags = "*"
cfg-if = "*"
static_assertions = "0.3.1"

[dependencies.num-traits]
version = "0.2"
default-features = false

[target.'cfg(target_vendor = "host")'.dependencies]
libc = { version = "0.2", default-features = false }
